=head1 NAME

cpod - cron(8) friendly podcatcher

=head1 SYNOPSIS

B<cpod> [B<-h>] [B<-r> I<number>] [B<-t> I<number>] [B<-v>]

=head1 DESCRIPTION

cpod is a small cron friendly podcatcher written in go(1). It uses a
tiny json file to store your feeds but it doesn't track downloaded
episodes.  When your are done with a podcast episode you can delete it
and cpod won't fetch it again.

If you don't pass any command line flags to cpod it will automatically
update all feeds and download all new episodes. However, the options
described below might be used to change this behaviour.

cpod is using a plain text file to store your podcast subscriptions. You need
to manually create this file before starting cpod for the first time. Open the
file with your favorite text editor and add your desired URLs (one per line).
The file path is documented in the B<FILE> section below.

Previous version of cpod supported opml import and export, however this
feature was removed later on. Nowadays two scripts are provided for
handling opml files, those scripts can be found in the contrib folder in
the source tree.

=head1 OPTIONS

=over 4

=item B<-h>

Display help and exit.

=item B<-r> I<number>

Number of most recent episodes to download.

=item B<-t> I<number>

Number of times a failed download is retried.

=item B<-v>

Display version number and exit.

=back

=head1 ENVIRONMENT

=over 4

=item CPOD_DOWNLOAD_DIR

The download directory (default: ~/podcasts).

=item HOME

Used as a fallback to determine path of users home directory.

=item XDG_CACHE_HOME

Base directory with non-essential data files (default ~/.cache).

=item XDG_CONFIG_HOME

Base directory with config files (default: ~/.config).

=back

=head1 FILES

=over 4

=item $CPOD_DOWNLOAD_DIR

Directory with downloaded podcast episodes.

=item $XDG_CACHE_HOME/cpod/lock

Lock file used to ensure that cpod isn't invoked twice.

=item $XDG_CONFIG_HOME/cpod/urls

Plain text file containing all subscribed feeds.

=back

=head1 SEE ALSO

go(1), cron(8)
