=head1 NAME

cpod-export - OPML export for cpod(1)

=head1 SYNOPSIS

B<cpod-export> I<URLFILE>B<...>

=head1 DESCRIPTION

cpod-export reads the specfied url files line by line, fetches each
feed and transform it into an OPML outline. Afterwards those OPML
outlines are combined into an OPML XML document and written to stdout.
You could redirect stdout to a file in order to create an OPML file
which can then be imported by a different application.

It uses goroutines to fetch all feeds concurrently and is thus
relatively fast. If you want to import an existing OPML file take a look
at cpod-import(1).

=head1 SEE ALSO

cpod(1), cpod-import(1)
