=head1 NAME

cpod-import - OPML import for cpod(1)

=head1 SYNOPSIS

B<cpod-import> I<OPMLFILE>B<...>

=head1 DESCRIPTION

cpod-import imports your subscriptions from the specified OPML files.
After parsing the files it writes each outline to stdout. You could
redirect stdout to file in order to create an url file which can be
imported by cpod(1). If you want to export an existing OPML file take a
look at cpod-export(1).

=head1 SEE ALSO

cpod(1), cpod-export(1)
